[tool.black]
line-length = 79
include = '\.py$'
experimental-string-processing = true

[tool.towncrier]
issue_format = ""
directory = "changes"
package = "ckanext.syndicate"
package_dir = "ckanext"
filename = "CHANGELOG.rst"
name = "ckanext-syndicate"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::sqlalchemy.exc.SADeprecationWarning",
    "ignore::sqlalchemy.exc.SAWarning",
    "ignore::DeprecationWarning",
    "ignore::bs4.GuessedAtParserWarning"  # using lxml as default parser
]


addopts = "--ckan-ini test.ini"
